source 'https://rubygems.org'
gem 'activerecord', require: 'active_record'
gem 'async-websocket', '~> 0.8.0'
gem 'minitest'
gem 'otr-activerecord'
gem 'pagy_cursor'
gem 'pg'
gem 'rake'
gem 'rubocop'
gem 'slack-ruby-bot-server'
gem 'slack-ruby-bot-server-events'
gem 'slack-ruby-client'
